version: '3'

services:
  api01: &api
    hostname: api01
    restart: always
    ports:
      - "3000:3000"
    image: felipph/nodejs-rinha24q1
    build: .
    depends_on:
      - database
    volumes:
      - ./src/server.js:/usr/app/server.js
    command: node server.js
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "60MB"
  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api 
    hostname: api02
    ports:
      - "3001:3000"  
  proxy:
    hostname: proxy
    image: haproxy
    restart: always
    ports:
      - "9999:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
  database:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/01-create.sql
    # command: postgres -c max_connections=20 -c log_error_verbosity='TERSE' -c log_min_error_statement='LOG' 
    command: postgres -c max_connections=20 
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "410M"

# networks:
#   default:
#     driver: bridge
#     name: rinha-nginx-2024q1